name = "commandv"
compatibility_date = "2024-09-19"
assets = { directory = "./dist/", not_found_handling = "none" }

# D1 database binding (fill with your actual database details)
# Create with: wrangler d1 create commandv
# Then update database_id below or via environment-specific sections.
#
# [[d1_databases]]
# binding = "DB"
# database_name = "commandv"
# database_id = "REPLACE_WITH_YOUR_DATABASE_ID"

# R2 bucket binding for OGP thumbnails (fill with your bucket name)
# Create with: wrangler r2 bucket create commandv-ogp
#
# [[r2_buckets]]
# binding = "R2"
# bucket_name = "commandv-ogp"

[vars]
# Used by sample /api/clock and also for session signing when not provided.
MY_VAR = "Hello from Cloudflare Workers!"
SESSION_SECRET = "CHANGE_ME_TO_RANDOM_32B"
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
# Optional: override callback
GOOGLE_REDIRECT_URI = ""
